CREATE OR REPLACE PROCEDURE DELETE_USER (P_USR_ID INT) LANGUAGE PLPGSQL AS $$
BEGIN
   DELETE 
	FROM TBL_USER USR 
    WHERE USR.USR_ID = P_USR_ID;

	EXCEPTION 
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Erro ao deletar usuário: %', SQLERRM;
END;
$$;