CREATE OR REPLACE PROCEDURE DELETE_CUSTOMER (P_CST_ID INT) LANGUAGE PLPGSQL AS $$
BEGIN
   DELETE FROM TBL_ADDRESS ADR
    WHERE ADR.CST_ID = P_CST_ID;

   DELETE FROM TBL_CUSTOMER CST
    WHERE CST.CST_ID = P_CST_ID;

	EXCEPTION 
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Erro ao deletar cliente e endereço: %', SQLERRM;
END;
$$;