CREATE OR REPLACE PROCEDURE INSERT_USER (
	P_NAME VARCHAR,
	P_EMAIL VARCHAR,
	P_PASSWORD VARCHAR,
	P_ID_USER INT
) LANGUAGE PLPGSQL AS $$
BEGIN
    INSERT INTO TBL_USER (USR_NAME, USR_EMAIL, USR_PASSWORD, CREATION_DATE, CREATED_BY) 
    VALUES (P_NAME, P_EMAIL, P_PASSWORD, CURRENT_TIMESTAMP, P_ID_USER);    

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Erro ao inserir usuário: %', SQLERRM;
END;
$$;