CREATE OR REPLACE PROCEDURE INSERT_CUSTOMER(
    P_NAME VARCHAR,
    P_CPF VARCHAR,
    P_EMAIL VARCHAR,
    P_PHONE VARCHAR,
    P_ZIP_CODE VARCHAR,
    P_STREET VARCHAR,
    P_NUMBER INT,
    P_COMPLEMENT VARCHAR,
    P_CITY VARCHAR,
    P_STATE VARCHAR,
	P_ID_USER INT
	)
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_CST_ID INTEGER;
BEGIN
    INSERT INTO TBL_CUSTOMER (CST_NAME, CST_CPF, CST_EMAIL, CST_PHONE, CREATION_DATE, CREATED_BY) 
    VALUES (P_NAME, P_CPF, P_EMAIL, P_PHONE, CURRENT_TIMESTAMP, P_ID_USER)
    RETURNING CST_ID INTO V_CST_ID;

    INSERT INTO TBL_ADDRESS (CST_ID, ADR_ZIP_CODE, ADR_STREET, ADR_NUMBER, ADR_COMPLEMENT, ADR_CITY, ADR_STATE, CREATION_DATE, CREATED_BY) 
    VALUES (V_CST_ID, P_ZIP_CODE, P_STREET, P_NUMBER, P_COMPLEMENT, P_CITY, P_STATE, CURRENT_TIMESTAMP, P_ID_USER);

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Erro ao inserir cliente e endereço: %', SQLERRM;
END;
$$;