CREATE OR REPLACE PROCEDURE INSERT_PRODUCT(
    P_NAME VARCHAR,
    P_PRICE DECIMAL,
    P_STOCK INT,
    P_ID_USER INT
) LANGUAGE PLPGSQL
AS $$

BEGIN
    INSERT INTO TBL_PRODUCT (PRD_NAME, PRD_PRICE, PRD_STOCK, CREATION_DATE, CREATED_BY) 
    VALUES (P_NAME, P_PRICE, P_STOCK, CURRENT_TIMESTAMP, P_ID_USER);    

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Erro ao inserir produto: %', SQLERRM;
END;
$$;