CREATE OR REPLACE FUNCTION SELECT_CUSTOMER(P_CST_ID int, P_OPTION int)
RETURNS REFCURSOR AS $$
DECLARE 
    CURSOR_CUSTOMER REFCURSOR;
BEGIN
    IF (P_OPTION = 1) THEN
       OPEN CURSOR_CUSTOMER FOR
     SELECT CST.CST_ID, 
            CST.CST_NAME, 
            CST.CST_CPF, 
            CST.CST_EMAIL, 
            CST.CST_PHONE,
            ADR.ADR_ZIP_CODE,
            ADR.ADR_STREET,
            ADR.ADR_NUMBER,
            ADR.ADR_COMPLEMENT,
            ADR.ADR_CITY,
            ADR.ADR_STATE
       FROM TBL_CUSTOMER CST
 INNER JOIN TBL_ADDRESS ADR
         ON CST.CST_ID = ADR.CST_ID;
 
    ELSIF (P_OPTION = 2) THEN
       OPEN CURSOR_CUSTOMER FOR
     SELECT CST.CST_ID, 
            CST.CST_NAME, 
            CST.CST_CPF, 
            CST.CST_EMAIL, 
            CST.CST_PHONE,
            ADR.ADR_ZIP_CODE,
            ADR.ADR_STREET,
            ADR.ADR_NUMBER,
            ADR.ADR_COMPLEMENT,
            ADR.ADR_CITY,
            ADR.ADR_STATE
       FROM TBL_CUSTOMER CST
 INNER JOIN TBL_ADDRESS ADR
         ON CST.CST_ID = ADR.CST_ID
      WHERE CST.CST_ID = P_CST_ID;
    END IF;
END;
$$ LANGUAGE PLPGSQL;