CREATE OR REPLACE FUNCTION SELECT_USER(P_USR_ID INT, P_EMAIL VARCHAR, P_PASSWORD VARCHAR, P_OPTION INT)
RETURNS TABLE(USR_ID INT, USR_NAME VARCHAR, USR_EMAIL VARCHAR) AS $$
BEGIN
    -- RETORNA TODOS REGISTROS
    IF (P_OPTION = 1) THEN
     RETURN QUERY
     SELECT USR_ID,
            USR_NAME,
            USR_EMAIL
       FROM TBL_USER;
    
    -- RETORNA OS DADOS DE UM USUÁRIO (FILTRA ID)
    ELSIF (P_OPTION = 2) THEN
     RETURN QUERY
     SELECT USR_ID,
            USR_NAME,
            USR_EMAIL
       FROM TBL_USER
      WHERE USR_ID = P_USR_ID;

    -- LOGIN
    ELSIF (P_OPTION = 3) THEN
     RETURN QUERY
     SELECT USR_ID,
            USR_NAME,
            USR_EMAIL
       FROM TBL_USER
      WHERE USR_EMAIL    = P_EMAIL
        AND USR_PASSWORD = P_PASSWORD;

    -- ID E SENHA (ALTERAR SENHA)        
    ELSIF (P_OPTION = 4) THEN
     RETURN QUERY
     SELECT USR_ID,
            USR_NAME,
            USR_EMAIL
       FROM TBL_USER
      WHERE USR_ID       = P_USR_ID
        AND USR_PASSWORD = P_PASSWORD;
       END IF;
END;
$$ LANGUAGE PLPGSQL;