CREATE OR REPLACE PROCEDURE UPDATE_PASSWORD (
	P_USR_ID INT, 
	P_PASSWORD VARCHAR, 
	P_ID_USER INT
) LANGUAGE PLPGSQL AS $$
BEGIN
	UPDATE TBL_USER USR
	   SET USR.USR_PASSWORD = P_PASSWORD,
		   USR.MODIFIED_DATE = CURRENT_TIMESTAMP,
		   USR.MODIFIED_BY = P_ID_USER
	 WHERE USR.USR_ID = P_USR_ID;

	EXCEPTION 
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Erro ao alterar senha: %', SQLERRM;
END;
$$;