CREATE OR REPLACE PROCEDURE UPDATE_PRODUCT(
    P_PRD_ID INT,
    P_NAME VARCHAR,
    P_PRICE DECIMAL,
    P_STOCK INT,
    P_ID_USER INT
) LANGUAGE PLPGSQL
AS $$

BEGIN
    UPDATE TBL_PRODUCT PRD
       SET PRD.PRD_NAME = P_NAME,
           PRD.PRD_PRICE = P_PRICE,
           PRD.PRD_STOCK = P_STOCK,
           PRD.MODIFIED_DATE = CURRENT_TIMESTAMP,
           PRD.MODIFIED_BY = P_ID_USER
     WHERE PRD.PRD_ID = P_PRD_ID;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE EXCEPTION 'Erro ao atualizar produto: %', SQLERRM;
END;
$$;